In [15]:
import mlflow 
# Step 2: Set up the MLflow tracking server
mlflow.set_tracking_uri("http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/")

In [16]:
# Set or create an experiment
mlflow.set_experiment("Exp 2 - BoW vs TfIdf")

<Experiment: artifact_location='s3://my-s3-bucket-of-store-artifact-youtube-data12/mlflow-artifacts/4', creation_time=1763802276791, experiment_id='4', last_update_time=1763802276791, lifecycle_stage='active', name='Exp 2 - BoW vs TfIdf', tags={}>

In [17]:
import pandas as pd
df=pd.read_csv('sentiment_clean.csv')

In [18]:
df['sentiment_numeric'] = df.pop('sentiment_numeric')

In [19]:
df.head()

,text_clean,word_count,num_stop_words,num_chars,num_punctuation_chars,category_gaming,category_movies,category_music,category_technology,hour,...,anger,anticipation,trust,surprise,positive,negative,sadness,disgust,joy,sentiment_numeric
0,all products can be found on since i review 5...,24,9,116,1,0.0,0.0,0.0,1.0,19,...,0.0,0.0,0.333333,0.0,0.333333,0.0,0.0,0.0,0.333333,1
1,bro how to talk to woman in 6 steps is so rela...,12,5,53,0,0.0,0.0,0.0,1.0,23,...,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000,0
2,i was gonna say does it give you the drinks fo...,12,7,54,1,0.0,0.0,0.0,1.0,16,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0
3,anyone gonna talk abt what was o. his pc,9,3,40,1,0.0,0.0,0.0,1.0,22,...,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000,0
4,how is everyone not talking about his search?!...,15,6,85,4,0.0,0.0,0.0,1.0,12,...,0.0,0.0,0.000000,0.0,0.500000,0.0,0.0,0.0,0.500000,-1

In [20]:
X_numeric = df.iloc[:,1:-1]

In [21]:
X_numeric

,word_count,num_stop_words,num_chars,num_punctuation_chars,category_gaming,category_movies,category_music,category_technology,hour,weekday,...,fear,anger,anticipation,trust,surprise,positive,negative,sadness,disgust,joy
0,24,9,116,1,0.0,0.0,0.0,1.0,19,5,...,0.0,0.0,0.0,0.333333,0.0,0.333333,0.0,0.0,0.0,0.333333
1,12,5,53,0,0.0,0.0,0.0,1.0,23,2,...,0.0,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000
2,12,7,54,1,0.0,0.0,0.0,1.0,16,1,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
3,9,3,40,1,0.0,0.0,0.0,1.0,22,0,...,0.0,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000
4,15,6,85,4,0.0,0.0,0.0,1.0,12,0,...,0.0,0.0,0.0,0.000000,0.0,0.500000,0.0,0.0,0.0,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49472,6,0,30,0,0.0,0.0,0.0,0.0,9,1,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
49473,7,0,34,1,0.0,0.0,0.0,0.0,9,1,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
49474,8,0,45,0,0.0,0.0,0.0,0.0,9,1,...,0.0,0.0,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
49475,7,1,38,0,0.0,0.0,0.0,0.0,9,1,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
49476,4,0,25,1,0.0,0.0,0.0,0.0,9,1,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000

In [22]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import mlflow
import mlflow.sklearn
import scipy.sparse as sp
import numpy as np

# -----------------------------
# 1️⃣ Define numeric features


X_numeric = df.iloc[:,1:-1]
y = df['sentiment_numeric']

# Scale numeric features
scaler = StandardScaler()
X_numeric_scaled = scaler.fit_transform(X_numeric)

# -----------------------------
# 2️⃣ Train-test split (once!)
# -----------------------------
X_train_num, X_test_num, y_train, y_test, train_idx, test_idx = train_test_split(
    X_numeric_scaled, y, df.index, test_size=0.2, random_state=42, stratify=y
)

# -----------------------------
# 3️⃣ Include text features for the same train/test indices
# -----------------------------
df_train_text = df.loc[train_idx, 'text_clean']
df_test_text = df.loc[test_idx, 'text_clean']

# -----------------------------
# 4️⃣ Run experiment function
# -----------------------------
best_accuracy = 0
best_run_info = {}

def run_experiment(vectorizer_type, ngram_range, vectorizer_max_features, n_estimators=200, max_depth=15):
    global best_accuracy, best_run_info

    # Vectorization
    if vectorizer_type == "BoW":
        vectorizer = CountVectorizer(ngram_range=ngram_range, max_features=vectorizer_max_features)
    else:
        vectorizer = TfidfVectorizer(ngram_range=ngram_range, max_features=vectorizer_max_features)

    # Fit and transform text
    X_train_vec = vectorizer.fit_transform(df_train_text)
    X_test_vec = vectorizer.transform(df_test_text)

    # Convert numeric features to sparse and combine
    X_train_sparse = sp.hstack([X_train_vec, sp.csr_matrix(X_train_num)])
    X_test_sparse = sp.hstack([X_test_vec, sp.csr_matrix(X_test_num)])

    # -----------------------------
    # MLflow experiment
    # -----------------------------
    with mlflow.start_run() as run:
        run_name = f"{vectorizer_type}_{ngram_range}_{n_estimators}trees"
        mlflow.set_tag("mlflow.runName", run_name)
        mlflow.set_tag("experiment_type", "feature_engineering")
        mlflow.set_tag("model_type", "RandomForestClassifier")

        # Log params
        mlflow.log_params({
            "vectorizer_type": vectorizer_type,
            "ngram_range": ngram_range,
            "vectorizer_max_features": vectorizer_max_features,
            "numeric_features_count": X_train_num.shape[1],
            "n_estimators": n_estimators,
            "max_depth": max_depth
        })

        # Train model
        model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,          
        min_samples_leaf=2,      # default
        max_features='sqrt',     # sqrt of total features works well for text
        random_state=42,
        class_weight='balanced',
        n_jobs=-1
        )

        model.fit(X_train_sparse, y_train)

        # Predictions & metrics
        y_pred = model.predict(X_test_sparse)
        accuracy = accuracy_score(y_test, y_pred)
        mlflow.log_metric("accuracy", accuracy)

        # Log classification metrics
        classification_rep = classification_report(y_test, y_pred, output_dict=True)
        for label, metrics in classification_rep.items():
            if isinstance(metrics, dict):
                for metric, value in metrics.items():
                    mlflow.log_metric(f"{label}_{metric}", value)

        # Confusion matrix
        conf_matrix = confusion_matrix(y_test, y_pred)
        plt.figure(figsize=(8,6))
        sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
        plt.xlabel("Predicted")
        plt.ylabel("Actual")
        plt.title(f"Confusion Matrix: {vectorizer_type}, {ngram_range}")
        plt.savefig("confusion_matrix.png")
        mlflow.log_artifact("confusion_matrix.png")
        plt.close()

        # Log model
        mlflow.sklearn.log_model(model, f"random_forest_model_{vectorizer_type}_{ngram_range}_{n_estimators}trees")

        # Update best run
        if accuracy > best_accuracy:
            best_accuracy = accuracy
            best_run_info = {
                "vectorizer": vectorizer_type,
                "ngram_range": ngram_range,
                "n_estimators": n_estimators,
                "max_depth": max_depth,
                "accuracy": accuracy,
                "run_id": run.info.run_id
            }

# -----------------------------
# 5️⃣ Run all experiments
# -----------------------------
ngram_ranges = [(1,1), (1,2), (1,3)]
vectorizers = ["BoW", "TF-IDF"]
n_estimators_list = [100, 200, 300]

for vectorizer_type in vectorizers:
    for ngram in ngram_ranges:
        for n_est in n_estimators_list:
            run_experiment(vectorizer_type, ngram, vectorizer_max_features=5000, n_estimators=n_est)


print(" Best Run Info:")
print(best_run_info)

2025/11/22 15:56:22 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 15:57:00 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run BoW_(1, 1)_100trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/dd8e1baec0c74968bdeaafdf07beb2a4
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:02:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:02:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run BoW_(1, 1)_200trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/789b22c29e4d41e7bcfa7aa8c18c4932
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:13:13 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:15:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run BoW_(1, 1)_300trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/3909200048624689b000b0446e79931c
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:20:26 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:21:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run BoW_(1, 2)_100trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/a53a5914da374fee88c7feb3fcd59e1f
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:22:26 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:22:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run BoW_(1, 2)_200trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/4d142479baac48d3a8444e8587912245
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:25:32 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:26:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run BoW_(1, 2)_300trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/378be0688a044475be9dc6e4837c0692
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:28:29 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:30:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run BoW_(1, 3)_100trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/850d5e056e234c5dbd95a1fcf4d0591e
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:32:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:32:39 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run BoW_(1, 3)_200trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/3add2dd51a804bcb977964e8e16b6c27
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:34:53 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:35:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run BoW_(1, 3)_300trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/92db635d2d9745fe8661fb974499fd62
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:36:51 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:37:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run TF-IDF_(1, 1)_100trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/843bf396abc048f1a32a770458fa27c4
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:38:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:38:37 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run TF-IDF_(1, 1)_200trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/e45b3f67b40f4e468167f519fe98bc28
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:40:38 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:43:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run TF-IDF_(1, 1)_300trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/e0084a1887184b08b0ae1c50c471d274
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:45:20 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:46:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run TF-IDF_(1, 2)_100trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/cef46d3e68d34ab488e860ecd57a8f89
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:47:44 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:48:25 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run TF-IDF_(1, 2)_200trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/3caada1cffa04ddebdf7fd86d287a171
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 16:54:43 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 16:55:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run TF-IDF_(1, 2)_300trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/9e6c07d9e4d64b8bbad9c442991a07e6
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 17:00:23 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 17:00:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run TF-IDF_(1, 3)_100trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/fe1aacec70f345198a11c428c65814df
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 17:05:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 17:05:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run TF-IDF_(1, 3)_200trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/0165d35774f545eebb1aabc42734247d
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4

2025/11/22 17:07:52 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 17:08:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run TF-IDF_(1, 3)_300trees at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4/runs/c528515542424fab91d762c96e8f95e0
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/4
 Best Run Info:
{'vectorizer': 'TF-IDF', 'ngram_range': (1, 1), 'n_estimators': 200, 'max_depth': 15, 'accuracy': 0.6636014551333872, 'run_id': 'e45b3f67b40f4e468167f519fe98bc28'}