In [1]:
import mlflow 
# Step 2: Set up the MLflow tracking server
mlflow.set_tracking_uri("http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/")

In [2]:
# Set or create an experiment
mlflow.set_experiment("exp4-handle_imbalanced_data")

<Experiment: artifact_location='s3://my-s3-bucket-of-store-artifact-youtube-data12/mlflow-artifacts/6', creation_time=1763816497986, experiment_id='6', last_update_time=1763816497986, lifecycle_stage='active', name='exp4-handle_imbalanced_data', tags={}>

In [1]:
import pandas as pd

df=pd.read_csv('sentiment_clean.csv')

In [7]:
df[df['sentiment_numeric'].isna()]

Empty DataFrame
Columns: [text_clean, word_count, num_stop_words, num_chars, num_punctuation_chars, category_gaming, category_movies, category_music, category_technology, hour, weekday, month, fear, anger, anticipation, trust, surprise, positive, negative, sadness, disgust, joy, sentiment_numeric]
Index: []

[0 rows x 23 columns]

In [6]:
df['sentiment_numeric']=df.pop('sentiment_numeric')

In [7]:
df.head()

,text_clean,word_count,num_stop_words,num_chars,num_punctuation_chars,category_gaming,category_movies,category_music,category_technology,hour,...,anger,anticipation,trust,surprise,positive,negative,sadness,disgust,joy,sentiment_numeric
0,all products can be found on since i review 5...,24,9,116,1,0.0,0.0,0.0,1.0,19,...,0.0,0.0,0.333333,0.0,0.333333,0.0,0.0,0.0,0.333333,1
1,bro how to talk to woman in 6 steps is so rela...,12,5,53,0,0.0,0.0,0.0,1.0,23,...,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000,0
2,i was gonna say does it give you the drinks fo...,12,7,54,1,0.0,0.0,0.0,1.0,16,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0
3,anyone gonna talk abt what was o. his pc,9,3,40,1,0.0,0.0,0.0,1.0,22,...,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000,0
4,how is everyone not talking about his search?!...,15,6,85,4,0.0,0.0,0.0,1.0,12,...,0.0,0.0,0.000000,0.0,0.500000,0.0,0.0,0.0,0.500000,-1

In [8]:
# -------------------------------------------------------------
# Experiment 4: Comparing imbalance handling methods for sentiment prediction
# -------------------------------------------------------------
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE, ADASYN
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN
import matplotlib.pyplot as plt
import seaborn as sns
import mlflow
import mlflow.sklearn
import scipy.sparse as sp
import numpy as np

In [9]:
df[df['text_clean'].isna()]

Empty DataFrame
Columns: [text_clean, word_count, num_stop_words, num_chars, num_punctuation_chars, category_gaming, category_movies, category_music, category_technology, hour, weekday, month, fear, anger, anticipation, trust, surprise, positive, negative, sadness, disgust, joy, sentiment_numeric]
Index: []

[0 rows x 23 columns]

In [10]:
# -----------------------------
# 1️⃣ Prepare numeric + text data
# -----------------------------

X_numeric = df.iloc[:,1:-1]
y = df['sentiment_numeric']

# Scale numeric features
scaler = StandardScaler()
X_numeric_scaled = scaler.fit_transform(X_numeric)

# Train-test split (keep same split for fairness)
X_train_num, X_test_num, y_train, y_test, train_idx, test_idx = train_test_split(
    X_numeric_scaled, y, df.index, test_size=0.2, random_state=42, stratify=y
)

df_train_text = df.loc[train_idx, 'text_clean']
df_test_text = df.loc[test_idx, 'text_clean']

# -----------------------------
# 2️⃣ Function: Run an experiment for each imbalance technique
# -----------------------------
def run_imbalanced_experiment(imbalance_method):
    ngram_range = (1, 1)
    max_features = 2000  # best from Experiment 3

    # TF-IDF vectorization
    vectorizer = TfidfVectorizer(ngram_range=ngram_range, max_features=max_features)
    X_train_vec = vectorizer.fit_transform(df_train_text)
    X_test_vec = vectorizer.transform(df_test_text)

    # Combine text + numeric features
    X_train_sparse = sp.hstack([X_train_vec, sp.csr_matrix(X_train_num)])
    X_test_sparse = sp.hstack([X_test_vec, sp.csr_matrix(X_test_num)])

    # -----------------------------
    # Handle imbalance
    # -----------------------------
    class_weight = None
    if imbalance_method == 'class_weights':
        class_weight = 'balanced'
    else:
        if imbalance_method == 'oversampling':
            smote = SMOTE(random_state=42)
            X_train_sparse, y_train_bal = smote.fit_resample(X_train_sparse, y_train)
        
        elif imbalance_method == 'undersampling':
            rus = RandomUnderSampler(random_state=42)
            X_train_sparse, y_train_bal = rus.fit_resample(X_train_sparse, y_train)
        elif imbalance_method == 'smote_enn':
            smote_enn = SMOTEENN(random_state=42)
            X_train_sparse, y_train_bal = smote_enn.fit_resample(X_train_sparse, y_train)
        else:
            y_train_bal = y_train
    if imbalance_method == 'class_weights':
        y_train_bal = y_train  # original labels

    # -----------------------------
    # Train Random Forest
    # -----------------------------
    n_estimators = 200
    max_depth = 15

    with mlflow.start_run() as run:
        run_name = f"Imbalance_{imbalance_method}_TFIDF_2000feat"
        mlflow.set_tag("mlflow.runName", run_name)
        mlflow.set_tag("experiment_type", "imbalance_handling")
        mlflow.set_tag("model_type", "RandomForestClassifier")
        mlflow.set_tag("description", f"TF-IDF (1,1) + numeric features with {imbalance_method}")

        # Log parameters
        mlflow.log_params({
            "vectorizer_type": "TF-IDF",
            "ngram_range": ngram_range,
            "vectorizer_max_features": max_features,
            "imbalance_method": imbalance_method,
            "n_estimators": n_estimators,
            "max_depth": max_depth
        })

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            random_state=42,
            class_weight=class_weight,
            n_jobs=-1
        )
        model.fit(X_train_sparse, y_train_bal)

        # -----------------------------
        # Evaluation
        # -----------------------------
        y_pred = model.predict(X_test_sparse)
        accuracy = accuracy_score(y_test, y_pred)
        f1_macro = f1_score(y_test, y_pred, average='macro')
        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("f1_macro", f1_macro)

        # Classification report
        report = classification_report(y_test, y_pred, output_dict=True)
        for label, metrics in report.items():
            if isinstance(metrics, dict):
                for metric, value in metrics.items():
                    mlflow.log_metric(f"{label}_{metric}", value)

        # Confusion matrix
        labels = ['Negative (-1)', 'Neutral (0)', 'Positive (1)']
        conf_matrix = confusion_matrix(y_test, y_pred)
        plt.figure(figsize=(8,6))
        sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues", xticklabels=labels, yticklabels=labels)
        plt.xlabel("Predicted")
        plt.ylabel("Actual")
        plt.title(f"Confusion Matrix ({imbalance_method})")
        fname = f"conf_matrix_{imbalance_method}.png"
        plt.savefig(fname)
        mlflow.log_artifact(fname)
        plt.close()

        # Log model
        mlflow.sklearn.log_model(model, f"random_forest_tfidf_imbalance_{imbalance_method}")

        print(f" {imbalance_method}: Accuracy={accuracy:.3f}, F1={f1_macro:.3f}")


# -----------------------------
# 3️⃣ Run all imbalance methods
# -----------------------------
imbalance_methods = ['class_weights', 'oversampling', 'undersampling', 'smote_enn']
for method in imbalance_methods:
    run_imbalanced_experiment(method)

2025/11/22 19:52:18 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 19:53:11 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

 class_weights: Accuracy=0.672, F1=0.636
🏃 View run Imbalance_class_weights_TFIDF_2000feat at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/6/runs/8f7a2864b722422180ba1dc2502eb8f6
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/6

2025/11/22 20:14:35 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 20:16:27 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

 oversampling: Accuracy=0.674, F1=0.640
🏃 View run Imbalance_oversampling_TFIDF_2000feat at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/6/runs/e9045f4e54ad4f47b010b30cc3014b4b
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/6

2025/11/22 20:20:08 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 20:20:33 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

 undersampling: Accuracy=0.653, F1=0.618
🏃 View run Imbalance_undersampling_TFIDF_2000feat at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/6/runs/948a88972e7947e2b2fb6081a157b349
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/6

2025/11/22 20:38:32 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 20:43:55 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

 smote_enn: Accuracy=0.474, F1=0.441
🏃 View run Imbalance_smote_enn_TFIDF_2000feat at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/6/runs/f7dcdb0d2d9341b09f4e06ffdefed771
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/6